#before_script:
#  - ssh-keyscan -t rsa,dsa,ecdsa github.com > /etc/ssh/ssh_known_hosts
stages:
  - mirror
  
variables:
  MIRROR_REPOSITORY: "git@github.com:h44z/atestproject.git"

mirror-github:
  stage: mirror
  cache: {}
  script:
    # Do a mirror clone of the repository
    - git clone --mirror $CI_REPOSITORY_URL
    # Mirror push it to the destination
    - cd $CI_PROJECT_NAME.git
    - git push --mirror $MIRROR_REPOSITORY
    # Cleanup
    - cd ..; rm -rf $CI_PROJECT_NAME.git